### ISSUE TITLE
reflection warnings

### ISSUE THREAD

**Issue by tomconnors** [funcool/clojure.jdbc#34]
With version 0.9.0, the following code gets a reflection warning:
``` clojure
(with-open [conn (jdbc/connection my-connection-pool)]
   (do-anything conn))
```
I'm able to remove the reflection warnings by changing that to:
``` clojure
(with-open [^java.io.Closeable conn (jdbc/connection my-connection-pool)]
   (do-anything conn))
```
But I'm unsure whether there's a more specific type I should be hinting. If that's the right hint, would you take a PR adding the type hint to the implementation of `jdbc/connection`?

**Comment by niwinz** [comment]
Hmm, seems like this should be hinted on the user side, we can't type hint the `connection` function with `Closeable`. However your code is correct, in this concrete situation the connection behaves as closable so the hint is correct.
