### ISSUE TITLE
Wrong isolation level constants in documentation

### ISSUE THREAD

**Issue by serioga** [funcool/clojure.jdbc#37]
In documentation:

> This is a list of supported options:
> 
> * `:read-uncommited` - Set read uncommited isolation level
> * `:read-commited` - Set read committed isolation level

In code:

```clojure
{
   :read-uncommitted Connection/TRANSACTION_READ_UNCOMMITTED
   :read-committed   Connection/TRANSACTION_READ_COMMITTED
}
```

See the difference in double “t”.

**Comment by niwinz** [comment]
Thanks, fixed.
